# Generated by Django 4.2.2 on 2023-06-24 06:26

import django.core.validators
from django.db import migrations, models
import exam.web.validators


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fruit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, validators=[exam.web.validators.validate_fruit_name, django.core.validators.MinLengthValidator(2)], verbose_name='Name')),
                ('image_url', models.URLField()),
                ('description', models.TextField()),
                ('nutrition', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
